name: Test Webware for Python 3 package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      max-parallel: 6
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11', 'pypy-3.9']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[tests] --use-pep517
    - name: Lint with flake8
      if: matrix.python-version == '3.10'
      run: |
        flake8 webware setup.py --count --exit-zero --statistics
    - name: Lint with pylint
      if: matrix.python-version == '3.10'
      run: |
        pylint webware
    - name: Run all unit tests
      run: |
        cd webware
        python -m unittest discover -fv -p Test*.py
